Mobile view skeleton of portfolio page
sireclifford/Microverse-Student-Project-1 pull request #1
Opened 2022-05-26 13:34 UTC by sireclifford

I designed the mobile view of my portfolio page using HTML and CSS and checking for errors using linters.

The below linters were added to check for errors and correction.

- Lighthouse
- Webhint
- Stylelint

2022-05-26 14:08 UTC, KayLemba requested changes
Hi @sireclifford   👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-26 14:08 UTC, KayLemba commented on index.html
> +            </p>
While you did a good job implementing this your paragraght in leaning to much on the left hand side.
This is how your work looks: 
![Screenshot from 2022-05-26 17-51-53](https://user-images.githubusercontent.com/79506105/170502189-e990292b-ffe8-4595-bbd5-75c21343a0bd.png)
I recommend you set your width to auto or 100% and add a padding-left of about 8px. For example you can try and use this styling:
.hero-summary {
    height: 126px;
    width: auto;
    left: 16px;
    font-family: Poppins, sans-serif;
    font-size: 14px;
    font-weight: 400;
    line-height: 21px;
    letter-spacing: -0.01em;
    text-align: left;
    margin: 20px 0 40px 0;
    padding-left: 8px;

This is how you work will look:
![Screenshot from 2022-05-26 17-51-26](https://user-images.githubusercontent.com/79506105/170502947-decdda0d-c812-4b3e-b6e8-7312c047ee00.png)

Atleast this will make it look similar to the figma template you picked. Make a few adjustments and it will look like this 

FIGMA DESIGN:


![Screenshot from 2022-05-26 18-04-10](https://user-images.githubusercontent.com/79506105/170503506-d1a92839-b69d-4da2-a81d-523e52207155.png)
Your work should look similar to the image above

2022-05-26 14:08 UTC, KayLemba commented on index.html
> +            </h1>
kindly change the name Charlie Giorgania and raplace it with your full names for this portifolio you are building is yours and not Charlie's.

2022-05-26 14:19 UTC, sireclifford commented on index.html
> +            </p>
@KayLemba thank you for the highlights. It's difficult understanding what is meant by "your design should match figma". Whilst working on it, I wanted to do exactly how i saw it on the figma.

I will be very glad if you can direct me to a doc or any video that explains how to create a sight using Figma or if you have some pointers too, I will love to know.

For instance, when a margin is 10px in figma, must i multiply it by some value or must i use exactly the same values. I really want to understand the flow before i move on. However, i have implemented the changes.

Thank you.

2022-05-27 02:01 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Sire Clifford,  

Your project is complete! 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations! Kindly consider my comments marked OPTIONAL

## Highlights 👍
- Descriptive Pull Request
- Correct gitflow used
- No linter errors

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**_Kindly notice that these are required changes I'm sorry they didn't show up in the earlier review._**

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 02:01 UTC, rloterh commented on index.html
> +    <div class="wrapper">
- [x] OPTIONAL
To enforce proper use of HTML semantics, kindly ensure that the _toolbar_ section is wrapped with a `<header>` tag.

2022-05-27 02:01 UTC, rloterh commented on index.html
> +            <div class="logo">
- [x] OPTIONAL
To enforce proper use of HTML semantics, kindly ensure that the _logo_ section is wrapped with an `<a>` tag. This will ensure the logo behaves as a link.

2022-05-27 02:01 UTC, rloterh commented on index.html
> +            <img class="nav-icon" src="/assets/images/ic_menu.png" alt="menu-icon"/>
- [x] OPTIONAL
To enforce proper use of HTML semantics, kindly ensure that the _hamburger menu_ is wrapped with a `<nav>` tag.

2022-05-27 02:01 UTC, rloterh commented on index.html
> +        <div class="hero-content">
- [x]  OPTIONAL
To enforce proper use of HTML semantics, kindly ensure that the _headline_ section is wrapped with a `<section>` tag.

2022-05-27 02:01 UTC, rloterh commented on index.html
> +            </div>
- [ ] OPTIONAL
It's semantically recommended to use `<button>` tag for a button instead of a `<p>` tag.
- [x] To enforce proper use of HTML semantics, kindly ensure that the _button_ section is wrapped with an `<a>` tag.

2022-05-27 07:48 UTC, merged